
const SOCKET_MESSAGES = {
    SAVE_TOKEN: 'SAVE_TOKEN',
    SWITCH_CHANNEL: 'SWITCH_CHANNEL',
    GET_MESSAGES: 'GET_MESSAGES',
    GET_MESSAGES_RES: 'GET_MESSAGES_RES',
    POST_MESSAGE: 'POST_MESSAGE',
    POST_IMAGE: 'POST_IMAGE',
    POST_VIDEO: 'POST_VIDEO'
}

module.exports = {
    SOCKET_MESSAGES
}